const Ap_Courses = [
{name: 'AP Seminar'},
{name: 'AP Art History'},
{name: 'AP Biology'},
{name: 'AP Calculus AB'},
{name: 'AP Calculus BC'},
{name: 'AP Chemistry'},
{name: 'AP Chinese Language and Culture'},
{name: 'AP Computer Science A'},
{name: 'AP Computer Science Principles'},
{name: 'AP English Language and Composition'},
{name: 'AP English Literature and Composition'},
{name: 'AP Environmental Science'},
{name: 'AP European History'},
{name: 'AP French Language and Culture'},
{name: 'AP German Language and Culture'},
{name: 'AP Government and Politics (Comparative)'},
{name: 'AP Government and Politics (US)'},
{name: 'AP Human Geography'},
{name: 'AP Italian Language and Culture'},
{name: 'AP Japanese Language and Culture'},
{name: 'AP Latin'},
{name: 'AP Macroeconomics'},
{name: 'AP Microeconomics'},
{name: 'AP Music Theory'},
{name: 'AP Physics 1: Algebra-Based'},
{name: 'AP Physics 2: Algebra-Based'},
{name: 'AP Physics C: Electricity and Magnetism'},
{name: 'AP Physics C: Mechanics'},
{name: 'AP Psychology'},
{name: 'AP Spanish Language and Culture'},
{name: 'AP Spanish Literature and Culture'},
{name: 'AP Statistics'},
{name: 'AP Studio Art Drawing'},
{name: 'AP Studio Art 2-D Design'},
{name: 'AP Studio Art 3-D Design'},
{name: 'AP US History'},
{name: 'AP World History (Modern)'}

];

export default Ap_Courses;