const MajorList = [
    {name: 'Anthropological (Archaeology) (B.A.)'},
    {name: 'Anthropology (Biological Anthropology) (B.A.)'},
    {name: 'Anthropology (Climate Change and Human Solutions) (B.A.)'},
    {name: 'Anthropology (Sociocultural Anthropology) (B.A.)'},
    {name: 'Biological Anthropology (B.S.)'},
    
    {name: 'Bioengineering (B.S.)'},
    {name: 'Bioengineering: Biotechnology (B.S.)'},
    {name: 'Bioengineering: Bioinformatics (B.S.)'},
    {name: 'Bioengineering: BioSystems (B.S.)'},
    
    {name: 'General Biology (B.S.)'},
    {name: 'Biology with a Specialization in Bioinformatics (B.S.)'},
    {name: 'Ecology, Behavior, and Evolution (B.S.)'},
    {name: 'Human Biology (B.S.)'},
    {name: 'Microbiology (B.S.)'},
    {name: 'Molecular and Cell Biology (B.S.)'},
    {name: 'Neurobiology (B.S.)'},
    
    {name: 'Chemistry (B.S.)'},
    {name: 'Chemistry with Specialization in Earth Sciences (B.S.)'},
    {name: 'Biochemistry/Chemistry (B.S.)'},
    {name: 'Environmental Chemistry (B.S.)'},
    {name: 'Molecular Synthesis (B.S.)'},
    {name: 'Pharmacological Chemistry (B.S.)'},
    {name: 'Bioinformatics (B.S.)'},
    
    {name: 'Cognitive Science (B.A.)/(B.S.)'},
    {name: 'Cognitive Science with Specialization in Clinical Aspects of Cognition (B.S.)'},
    {name: 'Cognitive Science with Specialization in Design and Interaction (B.S.)'},
    {name: 'Cognitive Science with Specialization in Machine Learning and Neural Computation (B.S.)'},
    {name: 'Cognitive Science with Specialization in Neuroscience (B.S.)'},
    {name: 'Cognitive Science with Specialization in Language and Culture (B.S.)'},
    {name: 'Cognitive and Behavioral Neuroscience (B.S.)'},

    {name: 'Communication (B.A.)'},

    {name: 'Computer Science (B.A.)/(B.S.)'},
    {name: 'Computer Engineering (B.S.)'},
    {name: 'Computer Science with Specialization in Bioinformatics (B.S.)'},

    {name: 'Economics (B.A.)'},
    {name: 'Economics–Public Policy (B.A.)/MPP only'},
    {name: 'Management Science (B.S.)'},
    {name: 'Joint Economics-Mathematics (B.S.)'},
    
    {name: 'Education Sciences (B.S.)'},
    
    {name: 'Electrical Engineering (B.S.)'},
    {name: 'Electrical Engineering and Society (B.A.)'},
    {name: 'Engineering Physics (B.S.)'},
    
    {name: 'Ethnic Studies (B.A.)'},
    
    {name: 'Public Health (B.S.)'},
    
    {name: 'Data Science (B.S.)'},
    
    {name: 'History (B.A.)'},
    
    {name: 'Linguistics (Cognition and Language) (B.A.)'},
    {name: 'Linguistics (Language and Society) (B.A.)'},
    {name: 'Linguistics (Speech and Language Sciences) (B.A.)'},
    {name: 'Language Studies (B.A.)'},
    {name: 'Linguistics (B.A.)'},
    
    {name: 'Literatures in English (B.A.)'},
    {name: 'Literatures in Spanish (B.A.)'},
    {name: 'Literature/Writing (B.A.)'},
    {name: 'World Literature and Culture (B.A.)'},
    
    {name: 'Mathematics (B.S.)'},
    {name: 'Mathematics (Applied) (B.S.)'},
    {name: 'Mathematics—Computer Science (B.S.)'},
    {name: 'Mathematics—Applied Science (B.S.)'},
    {name: 'Joint Mathematics-Economics (B.S.)'},
    {name: 'Mathematics—Scientific Computation (B.S.)'},
    {name: 'Mathematics—Secondary Education (B.A.)'},
    {name: 'Probability and Statistics (B.S.)'},
    
    {name: 'Aerospace Engineering (B.S.)'},
    {name: 'Environmental Engineering (B.S.)'},
    {name: 'Mechanical Engineering (B.S.)'},
    {name: 'Mechanical Engineering with a Specialization in Controls and Robotics (B.S.)'},
    {name: 'Mechanical Engineering with a Specialization in Fluid Mechanics and Thermal Systems (B.S.)'},
    {name: 'Mechanical Engineering with a Specialization in Materials Science and Engineering (B.S.)'},
    {name: 'Mechanical Engineering with a Specialization in Mechanics of Materials (B.S.)'},
    {name: 'Mechanical Engineering with a Specialization in Renewable Energy and Environmental Flows (B.S.)'},
    
    {name: 'Interdisciplinary Computing and the Arts (B.A.)'},
    {name: 'Music (B.A.)'},
    {name: 'Music/Humanities (B.A.)'},
    
    {name: 'Chemical Engineering (B.S.)'},
    {name: 'Nanoengineering (B.S.)'},
    
    {name: 'Philosophy (B.A.)'},
    
    {name: 'General Physics (B.A.)'},
    {name: 'General Physics/Secondary Education (B.A.)'},
    {name: 'Physics (B.S.)'},
    {name: 'Physics/Biophysics (B.S.)'},
    {name: 'Physics with Specialization in Computational Physics (B.S.)'},
    {name: 'Physics with Specialization in Earth Sciences (B.S.)'},
    {name: 'Physics with Specialization in Materials Physics (B.S.)'},
    {name: 'Physics with Specialization in Astrophysics (B.S.)'},
    
    {name: 'Political Science (B.A.)'},
    {name: 'Political Science (American Politics) (B.A.)'},
    {name: 'Political Science (Comparative Politics) (B.A.)'},
    {name: 'Political Science (International Relations) (B.A.)'},
    {name: 'Political Science (International Affairs) (B.A.)/MIA only'},
    {name: 'Political Science (Political Theory) (B.A.)'},
    {name: 'Political Science (Public Law) (B.A.)'},
    {name: 'Political Science (Public Policy) (B.A.)'},
    
    {name: 'Business Psychology (B.S.)'},
    {name: 'Cognitive and Behavioral Neuroscience Bachelor of Science (B.S.)'},
    {name: 'Psychology (B.A.)'},
    {name: 'Psychology (B.S.)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Clinical Psychology (B.S.)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Cognitive Psychology (B.S.)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Developmental Psychology (B.S.)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Human Health (B.S.)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Sensation and Perception (B.S.)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Social Psychology (B.S.)'},
    
    {name: 'Earth Sciences (B.S.)'},
    {name: 'Marine Biology (B.S.)'},
    {name: 'Oceanic and Atmospheric Sciences (B.S.)'},
    
    {name: 'Sociology (B.A.)'},
    {name: 'Sociology—International Studies (B.A.)'},
    {name: 'Sociology—American Studies (B.A.)'},
    {name: 'Sociology—Science and Medicine (B.A.)'},
    {name: 'Sociology—Economy and Society (B.A.)'},
    {name: 'Sociology—Culture and Communication (B.A.)'},
    {name: 'Sociology—Social Inequity (B.A.)'},
    {name: 'Sociology—Law and Society (B.A.)'},
    
    {name: 'Structural Engineering (B.S.)'},
    
    {name: 'Dance (B.A.)'},
    {name: 'Theatre (B.A.)'},
    
    {name: 'Urban Studies and Planning (B.A.)'},
    
    {name: 'Visual Arts (Art History/Criticism) (B.A.)'},
    {name: 'Visual Arts (Media) (B.A.)'},
    {name: 'Visual Arts (Studio) (B.A.)'},
    {name: 'Interdisciplinary Computing and the Arts (B.A.)'},
    {name: 'Speculative Design (B.A.)'},
    
    {name: 'Chinese Studies (B.A.)'},
    {name: 'Classical Studies (B.A.)'},
    {name: 'College Special Individual Majors (B.A.)'},
    {name: 'Critical Gender Studies (B.A.)'},
    {name: 'Environmental Systems—Earth Sciences (B.S.)'},
    {name: 'Environmental Systems—Ecology, Behavior and Evolution (B.S.)'},
    {name: 'Environmental Systems—Environmental Chemistry (B.S.)'},
    {name: 'Environmental Systems—Environmental Policy (B.A.)'},
    {name: 'German Studies (B.A.)'},
    {name: 'Global Health (B.A.)'},
    {name: 'Global Health (B.S.)'},
    {name: 'Global South Studies (B.A.)'},
    {name: 'Human Developmental Sciences (B.A.)'},
    {name: 'Human Developmental Sciences (B.S.)'},
    {name: 'Human Developmental Sciences with a Specialization in Equity and Diversity (B.S.)'},
    {name: 'Human Developmental Sciences with a Specialization in Healthy Aging (B.S.)'},
    {name: 'International Studies—Anthropology (B.A.)'},
    {name: 'International Studies—Economics (B.A.)'},
    {name: 'International Studies—History (B.A.)'},
    {name: 'International Studies—International Business (B.A.)'},
    {name: 'International Studies—Linguistics (B.A.)'},
    {name: 'International Studies—Literature (B.A.)'},
    {name: 'International Studies—Philosophy (B.A.)'},
    {name: 'International Studies—Political Science (B.A.)'},
    {name: 'International Studies—Sociology (B.A.)'},
    {name: '5-year International Studies—Economics (BA/MIA)'},
    {name: '5-year International Studies—International Business (BA/MIA)'},
    {name: '5-year International Studies—Political Science (BA/MIA)'},
    {name: 'Italian Studies (B.A.)'},
    {name: 'Japanese Studies (B.A.)'},
    {name: 'Jewish Studies (B.A.)'},
    {name: 'Latin American Studies (B.A.)'},
    {name: 'Latin American Studies with a Concentration in Mexico (B.A.)'},
    {name: 'Latin American Studies with a Concentration in Migration and Border Studies (B.A.)'},
    {name: 'Real Estate and Development (B.S.)'},
    {name: 'Russian, East European, and Eurasian Studies (B.A.)'},
    {name: 'Study of Religion (B.A.)'},

    {name: 'Undeclared'}
    ];

export default MajorList;

