const MajorList = [
    {name: 'Anthropological (Archaeology) (BA)'},
    {name: 'Anthropology (Biological Anthropology) (BA)'},
    {name: 'Anthropology (Climate Change and Human Solutions) (BA)'},
    {name: 'Anthropology (Sociocultural Anthropology) (BA)'},
    {name: 'Biological Anthropology (BS)'},
    
    {name: 'Bioengineering (BS)'},
    {name: 'Bioengineering: Biotechnology (BS)'},
    {name: 'Bioengineering: Bioinformatics (BS)'},
    {name: 'Bioengineering: BioSystems (BS)'},
    
    {name: 'General Biology (BS)'},
    {name: 'Biology with a Specialization in Bioinformatics (BS)'},
    {name: 'Ecology, Behavior, and Evolution (BS)'},
    {name: 'Human Biology (BS)'},
    {name: 'Microbiology (BS)'},
    {name: 'Molecular and Cell Biology (BS)'},
    {name: 'Neurobiology (BS)'},
    
    {name: 'Chemistry (BS)'},
    {name: 'Chemistry with Specialization in Earth Sciences (BS)'},
    {name: 'Biochemistry/Chemistry (BS)'},
    {name: 'Environmental Chemistry (BS)'},
    {name: 'Molecular Synthesis (BS)'},
    {name: 'Pharmacological Chemistry (BS)'},
    {name: 'Bioinformatics (BS)'},
    
    {name: 'Cognitive Science (BA)/(BS)'},
    {name: 'Cognitive Science with Specialization in Clinical Aspects of Cognition (BS)'},
    {name: 'Cognitive Science with Specialization in Design and Interaction (BS)'},
    {name: 'Cognitive Science with Specialization in Machine Learning and Neural Computation (BS)'},
    {name: 'Cognitive Science with Specialization in Neuroscience (BS)'},
    {name: 'Cognitive Science with Specialization in Language and Culture (BS)'},
    {name: 'Cognitive and Behavioral Neuroscience (BS)'},

    {name: 'Communication (BA)'},

    {name: 'Computer Science (BA)/(BS)'},
    {name: 'Computer Engineering (BS)'},
    {name: 'Computer Science with Specialization in Bioinformatics (BS)'},

    {name: 'Economics (BA)'},
    {name: 'Economics–Public Policy (BA)/MPP only'},
    {name: 'Management Science (BS)'},
    {name: 'Joint Economics-Mathematics (BS)'},
    
    {name: 'Education Sciences (BS)'},
    
    {name: 'Electrical Engineering (BS)'},
    {name: 'Electrical Engineering and Society (BA)'},
    {name: 'Engineering Physics (BS)'},
    
    {name: 'Ethnic Studies (BA)'},
    
    {name: 'Public Health (BS)'},
    
    {name: 'Data Science (BS)'},
    
    {name: 'History (BA)'},
    
    {name: 'Linguistics (Cognition and Language) (BA)'},
    {name: 'Linguistics (Language and Society) (BA)'},
    {name: 'Linguistics (Speech and Language Sciences) (BA)'},
    {name: 'Language Studies (BA)'},
    {name: 'Linguistics (BA)'},
    
    {name: 'Literatures in English (BA)'},
    {name: 'Literatures in Spanish (BA)'},
    {name: 'Literature/Writing (BA)'},
    {name: 'World Literature and Culture (BA)'},
    
    {name: 'Mathematics (BS)'},
    {name: 'Mathematics (Applied) (BS)'},
    {name: 'Mathematics—Computer Science (BS)'},
    {name: 'Mathematics—Applied Science (BS)'},
    {name: 'Joint Mathematics-Economics (BS)'},
    {name: 'Mathematics—Scientific Computation (BS)'},
    {name: 'Mathematics—Secondary Education (BA)'},
    {name: 'Probability and Statistics (BS)'},
    
    {name: 'Aerospace Engineering (BS)'},
    {name: 'Environmental Engineering (BS)'},
    {name: 'Mechanical Engineering (BS)'},
    {name: 'Mechanical Engineering with a Specialization in Controls and Robotics (BS)'},
    {name: 'Mechanical Engineering with a Specialization in Fluid Mechanics and Thermal Systems (BS)'},
    {name: 'Mechanical Engineering with a Specialization in Materials Science and Engineering (BS)'},
    {name: 'Mechanical Engineering with a Specialization in Mechanics of Materials (BS)'},
    {name: 'Mechanical Engineering with a Specialization in Renewable Energy and Environmental Flows (BS)'},
    
    {name: 'Interdisciplinary Computing and the Arts (BA)'},
    {name: 'Music (BA)'},
    {name: 'Music/Humanities (BA)'},
    
    {name: 'Chemical Engineering (BS)'},
    {name: 'Nanoengineering (BS)'},
    
    {name: 'Philosophy (BA)'},
    
    {name: 'General Physics (BA)'},
    {name: 'General Physics/Secondary Education (BA)'},
    {name: 'Physics (BS)'},
    {name: 'Physics/Biophysics (BS)'},
    {name: 'Physics with Specialization in Computational Physics (BS)'},
    {name: 'Physics with Specialization in Earth Sciences (BS)'},
    {name: 'Physics with Specialization in Materials Physics (BS)'},
    {name: 'Physics with Specialization in Astrophysics (BS)'},
    
    {name: 'Political Science (BA)'},
    {name: 'Political Science (American Politics) (BA)'},
    {name: 'Political Science (Comparative Politics) (BA)'},
    {name: 'Political Science (International Relations) (BA)'},
    {name: 'Political Science (International Affairs) (BA)/MIA only'},
    {name: 'Political Science (Political Theory) (BA)'},
    {name: 'Political Science (Public Law) (BA)'},
    {name: 'Political Science (Public Policy) (BA)'},
    
    {name: 'Business Psychology (BS)'},
    {name: 'Cognitive and Behavioral Neuroscience Bachelor of Science (BS)'},
    {name: 'Psychology (BA)'},
    {name: 'Psychology (BS)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Clinical Psychology (BS)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Cognitive Psychology (BS)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Developmental Psychology (BS)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Human Health (BS)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Sensation and Perception (BS)'},
    {name: 'Psychology Bachelor of Science with a Specialization in Social Psychology (BS)'},
    
    {name: 'Earth Sciences (BS)'},
    {name: 'Marine Biology (BS)'},
    {name: 'Oceanic and Atmospheric Sciences (BS)'},
    
    {name: 'Sociology (BA)'},
    {name: 'Sociology—International Studies (BA)'},
    {name: 'Sociology—American Studies (BA)'},
    {name: 'Sociology—Science and Medicine (BA)'},
    {name: 'Sociology—Economy and Society (BA)'},
    {name: 'Sociology—Culture and Communication (BA)'},
    {name: 'Sociology—Social Inequity (BA)'},
    {name: 'Sociology—Law and Society (BA)'},
    
    {name: 'Structural Engineering (BS)'},
    
    {name: 'Dance (BA)'},
    {name: 'Theatre (BA)'},
    
    {name: 'Urban Studies and Planning (BA)'},
    
    {name: 'Visual Arts (Art History/Criticism) (BA)'},
    {name: 'Visual Arts (Media) (BA)'},
    {name: 'Visual Arts (Studio) (BA)'},
    {name: 'Interdisciplinary Computing and the Arts (BA)'},
    {name: 'Speculative Design (BA)'},
    
    {name: 'Chinese Studies (BA)'},
    {name: 'Classical Studies (BA)'},
    {name: 'College Special Individual Majors (BA)'},
    {name: 'Critical Gender Studies (BA)'},
    {name: 'Environmental Systems—Earth Sciences (BS)'},
    {name: 'Environmental Systems—Ecology, Behavior and Evolution (BS)'},
    {name: 'Environmental Systems—Environmental Chemistry (BS)'},
    {name: 'Environmental Systems—Environmental Policy (BA)'},
    {name: 'German Studies (BA)'},
    {name: 'Global Health (BA)'},
    {name: 'Global Health (BS)'},
    {name: 'Global South Studies (BA)'},
    {name: 'Human Developmental Sciences (BA)'},
    {name: 'Human Developmental Sciences (BS)'},
    {name: 'Human Developmental Sciences with a Specialization in Equity and Diversity (BS)'},
    {name: 'Human Developmental Sciences with a Specialization in Healthy Aging (BS)'},
    {name: 'International Studies—Anthropology (BA)'},
    {name: 'International Studies—Economics (BA)'},
    {name: 'International Studies—History (BA)'},
    {name: 'International Studies—International Business (BA)'},
    {name: 'International Studies—Linguistics (BA)'},
    {name: 'International Studies—Literature (BA)'},
    {name: 'International Studies—Philosophy (BA)'},
    {name: 'International Studies—Political Science (BA)'},
    {name: 'International Studies—Sociology (BA)'},
    {name: '5-year International Studies—Economics (BA/MIA)'},
    {name: '5-year International Studies—International Business (BA/MIA)'},
    {name: '5-year International Studies—Political Science (BA/MIA)'},
    {name: 'Italian Studies (BA)'},
    {name: 'Japanese Studies (BA)'},
    {name: 'Jewish Studies (BA)'},
    {name: 'Latin American Studies (BA)'},
    {name: 'Latin American Studies with a Concentration in Mexico (BA)'},
    {name: 'Latin American Studies with a Concentration in Migration and Border Studies (BA)'},
    {name: 'Real Estate and Development (BS)'},
    {name: 'Russian, East European, and Eurasian Studies (BA)'},
    {name: 'Study of Religion (BA)'},

    {name: 'Undeclared'}
    ];

export default MajorList;

